title: Nial Dixon
email: nialdixon8@gmail.com
description: >- 
  MSc Advanced Computer Science student with experience in software engineering, AI, and data visualization.

baseurl: "" 
url: "https://www.nialdixon.com" 
linkedin_username: linkedin.com/in/nial-dixon

repository: nialdixon8/nialdixon8.github.io
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme 

sections:
  - Education
  - Work Experience
  - Projects
  - Interests
